api:
  schema_path: "https://api.swagger.spectracube.com/api/docs/imos"
  use_global_settings: true
  package_name: "imos"
  api_client_import: "lib/core/network/api_client.dart"

  
output:
  base_directory: "lib/data/generated"
  models_path: "models"
  repositories_path: "repositories"
  
generation:
  add_to_json: true
  add_logging: true
  null_safety: true
  
naming:
  model_suffix: ""
  repository_suffix: "Repository"
  
features:
  generate_toString: false
  generate_copyWith: false
  generate_equality: false