name: flutter_openapi_generator
description: A CLI tool to generate Flutter model classes and repository classes from OpenAPI JSON schema files
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  flutter_openapi_generator: flutter_openapi_generator.dart
